# SPDX-License-Identifier: GPL-3.0-only
"""Velvet Native Brain experimental local-cognition subsystem."""

from .attention import (
    AttentionAssessment,
    AttentionContext,
    AttentionEngine,
    ObservationMaturity,
)
from .brainstem import BrainstemDecision, BrainstemRouter
from .cognition import CognitiveDecision, CognitiveOutcome, ObservationEnvelope
from .conversation import render_no_llm_ghost_response
from .conversation_ingress import (
    CORE_CONVERSATION_MEANING_EVENT,
    CORE_CONVERSATION_SCHEMA_VERSION,
    LANGUAGE_CONVERSATION_SCHEMA_VERSION,
    LANGUAGE_CONVERSATION_TURN_EVENT,
    ConversationMeaningKind,
    ConversationWorkRequest,
    GroundedConversationMeaning,
    conversation_work_request_from_event,
    handle_conversation_turn,
)
from .curiosity import (
    CuriosityAssessment,
    CuriosityContext,
    CuriosityDisposition,
    CuriosityEngine,
    CuriosityThreadCandidate,
)
from .cycle import (
    CognitiveCycle,
    CognitiveCycleResult,
    CognitiveKey,
    CycleStage,
    CycleTraceEntry,
    KeyState,
)
from .distributed_body import (
    CandidateMode,
    DegradationMode,
    DistributedBodyPlanner,
    NodeAdvertisement,
    NodeAvailability,
    NodeTier,
    PlacementDisposition,
    WorkCandidate,
    WorkPlacementProposal,
    WorkRequirement,
)
from .expectations import (
    ExpectationAssessment,
    ExpectationCandidate,
    ExpectationContext,
    ExpectationDisposition,
    ExpectationEngine,
    ExpectationState,
)
from .handmaiden_stem import HandmaidenStem, StemResult
from .integrated_cycle import (
    IntegratedCognitiveCycle,
    IntegratedCycleContext,
    IntegratedCycleOutcome,
    IntegratedCycleResult,
    IntegratedCycleStage,
    IntegratedCycleTraceEntry,
)
from .intents import (
    IntentAssessment,
    IntentCandidate,
    IntentContext,
    IntentDisposition,
    IntentEngine,
    IntentKind,
    IntentState,
)
from .judgment import (
    ConfidenceBand,
    JudgmentAssessment,
    JudgmentContext,
    JudgmentDisposition,
    JudgmentEngine,
)
from .llm_adapter import LLMPolishRequest, OptionalLLMAdapter
from .memory import NativeMemoryNote
from .native_loop import NativeBrainResult, run_native_brain_ghost_loop
from .patterns import (
    PatternAssessment,
    PatternCandidate,
    PatternContext,
    PatternDisposition,
    PatternEngine,
    PatternState,
)
from .presence import PresenceContext, PresenceGate
from .safety import NativeBrainSafetyError, authority_report, validate_no_authority_payload
from .self_orientation import (
    IntegrityFinding,
    IntegrityReport,
    NoDriftIntegrityGate,
    PersonalityProfile,
    PreferenceProfile,
    SelfIdentity,
    SelfOrientation,
)
from .state import NativeBrainState
from .stems import RubyStem, VelourStem
from .working_state import DeferredThought, OpenThread, ThreadStatus

__all__ = [
    "AttentionAssessment",
    "AttentionContext",
    "AttentionEngine",
    "BrainstemDecision",
    "BrainstemRouter",
    "CORE_CONVERSATION_MEANING_EVENT",
    "CORE_CONVERSATION_SCHEMA_VERSION",
    "CandidateMode",
    "CognitiveCycle",
    "CognitiveCycleResult",
    "CognitiveDecision",
    "CognitiveKey",
    "CognitiveOutcome",
    "ConfidenceBand",
    "ConversationMeaningKind",
    "ConversationWorkRequest",
    "CuriosityAssessment",
    "CuriosityContext",
    "CuriosityDisposition",
    "CuriosityEngine",
    "CuriosityThreadCandidate",
    "CycleStage",
    "CycleTraceEntry",
    "DeferredThought",
    "DegradationMode",
    "DistributedBodyPlanner",
    "ExpectationAssessment",
    "ExpectationCandidate",
    "ExpectationContext",
    "ExpectationDisposition",
    "ExpectationEngine",
    "ExpectationState",
    "GroundedConversationMeaning",
    "HandmaidenStem",
    "IntegratedCognitiveCycle",
    "IntegratedCycleContext",
    "IntegratedCycleOutcome",
    "IntegratedCycleResult",
    "IntegratedCycleStage",
    "IntegratedCycleTraceEntry",
    "IntegrityFinding",
    "IntegrityReport",
    "IntentAssessment",
    "IntentCandidate",
    "IntentContext",
    "IntentDisposition",
    "IntentEngine",
    "IntentKind",
    "IntentState",
    "JudgmentAssessment",
    "JudgmentContext",
    "JudgmentDisposition",
    "JudgmentEngine",
    "KeyState",
    "LANGUAGE_CONVERSATION_SCHEMA_VERSION",
    "LANGUAGE_CONVERSATION_TURN_EVENT",
    "LLMPolishRequest",
    "NativeBrainResult",
    "NativeBrainSafetyError",
    "NativeBrainState",
    "NativeMemoryNote",
    "NodeAdvertisement",
    "NodeAvailability",
    "NodeTier",
    "NoDriftIntegrityGate",
    "ObservationEnvelope",
    "ObservationMaturity",
    "OpenThread",
    "OptionalLLMAdapter",
    "PatternAssessment",
    "PatternCandidate",
    "PatternContext",
    "PatternDisposition",
    "PatternEngine",
    "PatternState",
    "PersonalityProfile",
    "PlacementDisposition",
    "PreferenceProfile",
    "PresenceContext",
    "PresenceGate",
    "RubyStem",
    "SelfIdentity",
    "SelfOrientation",
    "StemResult",
    "ThreadStatus",
    "VelourStem",
    "WorkCandidate",
    "WorkPlacementProposal",
    "WorkRequirement",
    "authority_report",
    "conversation_work_request_from_event",
    "handle_conversation_turn",
    "render_no_llm_ghost_response",
    "run_native_brain_ghost_loop",
    "validate_no_authority_payload",
]
